spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deen_discovery
    username: root
    password: "Abdi4021"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

quizapi:
  token: 'GfgEkBbhzOrsgYsWHAEkwnnptkgTVIOrJ4KgIMdN'

